/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as SubmissionsRouteRouteImport } from './routes/submissions/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIndexRouteImport } from './routes/quiz/index'
import { Route as QuestionsIndexRouteImport } from './routes/questions/index'
import { Route as ChaptersIndexRouteImport } from './routes/chapters/index'
import { Route as QuizAddRouteImport } from './routes/quiz/add'
import { Route as QuizIdRouteImport } from './routes/quiz/$id'
import { Route as QuestionsAddRouteImport } from './routes/questions/add'
import { Route as ChaptersAddRouteImport } from './routes/chapters/add'
import { Route as ChaptersIdRouteImport } from './routes/chapters/$id'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as QuizEditIdRouteImport } from './routes/quiz/edit.$id'
import { Route as ChaptersEditIdRouteImport } from './routes/chapters/edit.$id'

const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsRouteRoute = SubmissionsRouteRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIndexRoute = ChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizAddRoute = QuizAddRouteImport.update({
  id: '/quiz/add',
  path: '/quiz/add',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsAddRoute = QuestionsAddRouteImport.update({
  id: '/questions/add',
  path: '/questions/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersAddRoute = ChaptersAddRouteImport.update({
  id: '/chapters/add',
  path: '/chapters/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIdRoute = ChaptersIdRouteImport.update({
  id: '/chapters/$id',
  path: '/chapters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizEditIdRoute = QuizEditIdRouteImport.update({
  id: '/quiz/edit/$id',
  path: '/quiz/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersEditIdRoute = ChaptersEditIdRouteImport.update({
  id: '/chapters/edit/$id',
  path: '/chapters/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRoute
  '/submissions': typeof SubmissionsRouteRoute
  '/users': typeof UsersRouteRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/chapters/$id': typeof ChaptersIdRoute
  '/chapters/add': typeof ChaptersAddRoute
  '/questions/add': typeof QuestionsAddRoute
  '/quiz/$id': typeof QuizIdRoute
  '/quiz/add': typeof QuizAddRoute
  '/chapters': typeof ChaptersIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/chapters/edit/$id': typeof ChaptersEditIdRoute
  '/quiz/edit/$id': typeof QuizEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRoute
  '/submissions': typeof SubmissionsRouteRoute
  '/users': typeof UsersRouteRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/chapters/$id': typeof ChaptersIdRoute
  '/chapters/add': typeof ChaptersAddRoute
  '/questions/add': typeof QuestionsAddRoute
  '/quiz/$id': typeof QuizIdRoute
  '/quiz/add': typeof QuizAddRoute
  '/chapters': typeof ChaptersIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/chapters/edit/$id': typeof ChaptersEditIdRoute
  '/quiz/edit/$id': typeof QuizEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRoute
  '/submissions': typeof SubmissionsRouteRoute
  '/users': typeof UsersRouteRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/chapters/$id': typeof ChaptersIdRoute
  '/chapters/add': typeof ChaptersAddRoute
  '/questions/add': typeof QuestionsAddRoute
  '/quiz/$id': typeof QuizIdRoute
  '/quiz/add': typeof QuizAddRoute
  '/chapters/': typeof ChaptersIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/chapters/edit/$id': typeof ChaptersEditIdRoute
  '/quiz/edit/$id': typeof QuizEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/submissions'
    | '/users'
    | '/auth/sign-in'
    | '/chapters/$id'
    | '/chapters/add'
    | '/questions/add'
    | '/quiz/$id'
    | '/quiz/add'
    | '/chapters'
    | '/questions'
    | '/quiz'
    | '/chapters/edit/$id'
    | '/quiz/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/submissions'
    | '/users'
    | '/auth/sign-in'
    | '/chapters/$id'
    | '/chapters/add'
    | '/questions/add'
    | '/quiz/$id'
    | '/quiz/add'
    | '/chapters'
    | '/questions'
    | '/quiz'
    | '/chapters/edit/$id'
    | '/quiz/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/submissions'
    | '/users'
    | '/auth/sign-in'
    | '/chapters/$id'
    | '/chapters/add'
    | '/questions/add'
    | '/quiz/$id'
    | '/quiz/add'
    | '/chapters/'
    | '/questions/'
    | '/quiz/'
    | '/chapters/edit/$id'
    | '/quiz/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRoute
  SubmissionsRouteRoute: typeof SubmissionsRouteRoute
  UsersRouteRoute: typeof UsersRouteRoute
  AuthSignInRoute: typeof AuthSignInRoute
  ChaptersIdRoute: typeof ChaptersIdRoute
  ChaptersAddRoute: typeof ChaptersAddRoute
  QuestionsAddRoute: typeof QuestionsAddRoute
  QuizIdRoute: typeof QuizIdRoute
  QuizAddRoute: typeof QuizAddRoute
  ChaptersIndexRoute: typeof ChaptersIndexRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  QuizIndexRoute: typeof QuizIndexRoute
  ChaptersEditIdRoute: typeof ChaptersEditIdRoute
  QuizEditIdRoute: typeof QuizEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/': {
      id: '/chapters/'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/add': {
      id: '/quiz/add'
      path: '/quiz/add'
      fullPath: '/quiz/add'
      preLoaderRoute: typeof QuizAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/add': {
      id: '/questions/add'
      path: '/questions/add'
      fullPath: '/questions/add'
      preLoaderRoute: typeof QuestionsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/add': {
      id: '/chapters/add'
      path: '/chapters/add'
      fullPath: '/chapters/add'
      preLoaderRoute: typeof ChaptersAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$id': {
      id: '/chapters/$id'
      path: '/chapters/$id'
      fullPath: '/chapters/$id'
      preLoaderRoute: typeof ChaptersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/edit/$id': {
      id: '/quiz/edit/$id'
      path: '/quiz/edit/$id'
      fullPath: '/quiz/edit/$id'
      preLoaderRoute: typeof QuizEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/edit/$id': {
      id: '/chapters/edit/$id'
      path: '/chapters/edit/$id'
      fullPath: '/chapters/edit/$id'
      preLoaderRoute: typeof ChaptersEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRoute,
  SubmissionsRouteRoute: SubmissionsRouteRoute,
  UsersRouteRoute: UsersRouteRoute,
  AuthSignInRoute: AuthSignInRoute,
  ChaptersIdRoute: ChaptersIdRoute,
  ChaptersAddRoute: ChaptersAddRoute,
  QuestionsAddRoute: QuestionsAddRoute,
  QuizIdRoute: QuizIdRoute,
  QuizAddRoute: QuizAddRoute,
  ChaptersIndexRoute: ChaptersIndexRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  QuizIndexRoute: QuizIndexRoute,
  ChaptersEditIdRoute: ChaptersEditIdRoute,
  QuizEditIdRoute: QuizEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
