/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as SubmissionsRouteRouteImport } from './routes/submissions/route'
import { Route as QuizRouteRouteImport } from './routes/quiz/route'
import { Route as QuestionsRouteRouteImport } from './routes/questions/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as ChaptersRouteRouteImport } from './routes/chapters/route'
import { Route as RouteRouteImport } from './routes/route'
import { Route as QuizAddRouteImport } from './routes/quiz/add'
import { Route as QuizIdRouteImport } from './routes/quiz/$id'
import { Route as ChaptersAddRouteImport } from './routes/chapters/add'
import { Route as ChaptersIdRouteImport } from './routes/chapters/$id'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as QuizEditIdRouteImport } from './routes/quiz/edit.$id'
import { Route as ChaptersEditIdRouteImport } from './routes/chapters/edit.$id'

const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsRouteRoute = SubmissionsRouteRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRouteRoute = QuizRouteRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRouteRoute = QuestionsRouteRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRouteRoute = ChaptersRouteRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRoute = RouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizAddRoute = QuizAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => QuizRouteRoute,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QuizRouteRoute,
} as any)
const ChaptersAddRoute = ChaptersAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => ChaptersRouteRoute,
} as any)
const ChaptersIdRoute = ChaptersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChaptersRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizEditIdRoute = QuizEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => QuizRouteRoute,
} as any)
const ChaptersEditIdRoute = ChaptersEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => ChaptersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/chapters': typeof ChaptersRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRoute
  '/questions': typeof QuestionsRouteRoute
  '/quiz': typeof QuizRouteRouteWithChildren
  '/submissions': typeof SubmissionsRouteRoute
  '/users': typeof UsersRouteRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/chapters/$id': typeof ChaptersIdRoute
  '/chapters/add': typeof ChaptersAddRoute
  '/quiz/$id': typeof QuizIdRoute
  '/quiz/add': typeof QuizAddRoute
  '/chapters/edit/$id': typeof ChaptersEditIdRoute
  '/quiz/edit/$id': typeof QuizEditIdRoute
}
export interface FileRoutesByTo {
  '/chapters': typeof ChaptersRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRoute
  '/questions': typeof QuestionsRouteRoute
  '/quiz': typeof QuizRouteRouteWithChildren
  '/submissions': typeof SubmissionsRouteRoute
  '/users': typeof UsersRouteRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/chapters/$id': typeof ChaptersIdRoute
  '/chapters/add': typeof ChaptersAddRoute
  '/quiz/$id': typeof QuizIdRoute
  '/quiz/add': typeof QuizAddRoute
  '/chapters/edit/$id': typeof ChaptersEditIdRoute
  '/quiz/edit/$id': typeof QuizEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof RouteRoute
  '/chapters': typeof ChaptersRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRoute
  '/questions': typeof QuestionsRouteRoute
  '/quiz': typeof QuizRouteRouteWithChildren
  '/submissions': typeof SubmissionsRouteRoute
  '/users': typeof UsersRouteRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/chapters/$id': typeof ChaptersIdRoute
  '/chapters/add': typeof ChaptersAddRoute
  '/quiz/$id': typeof QuizIdRoute
  '/quiz/add': typeof QuizAddRoute
  '/chapters/edit/$id': typeof ChaptersEditIdRoute
  '/quiz/edit/$id': typeof QuizEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/chapters'
    | '/dashboard'
    | '/questions'
    | '/quiz'
    | '/submissions'
    | '/users'
    | '/auth/sign-in'
    | '/chapters/$id'
    | '/chapters/add'
    | '/quiz/$id'
    | '/quiz/add'
    | '/chapters/edit/$id'
    | '/quiz/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chapters'
    | '/dashboard'
    | '/questions'
    | '/quiz'
    | '/submissions'
    | '/users'
    | '/auth/sign-in'
    | '/chapters/$id'
    | '/chapters/add'
    | '/quiz/$id'
    | '/quiz/add'
    | '/chapters/edit/$id'
    | '/quiz/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/chapters'
    | '/dashboard'
    | '/questions'
    | '/quiz'
    | '/submissions'
    | '/users'
    | '/auth/sign-in'
    | '/chapters/$id'
    | '/chapters/add'
    | '/quiz/$id'
    | '/quiz/add'
    | '/chapters/edit/$id'
    | '/quiz/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RouteRoute: typeof RouteRoute
  ChaptersRouteRoute: typeof ChaptersRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRoute
  QuestionsRouteRoute: typeof QuestionsRouteRoute
  QuizRouteRoute: typeof QuizRouteRouteWithChildren
  SubmissionsRouteRoute: typeof SubmissionsRouteRoute
  UsersRouteRoute: typeof UsersRouteRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/add': {
      id: '/quiz/add'
      path: '/add'
      fullPath: '/quiz/add'
      preLoaderRoute: typeof QuizAddRouteImport
      parentRoute: typeof QuizRouteRoute
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof QuizRouteRoute
    }
    '/chapters/add': {
      id: '/chapters/add'
      path: '/add'
      fullPath: '/chapters/add'
      preLoaderRoute: typeof ChaptersAddRouteImport
      parentRoute: typeof ChaptersRouteRoute
    }
    '/chapters/$id': {
      id: '/chapters/$id'
      path: '/$id'
      fullPath: '/chapters/$id'
      preLoaderRoute: typeof ChaptersIdRouteImport
      parentRoute: typeof ChaptersRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/edit/$id': {
      id: '/quiz/edit/$id'
      path: '/edit/$id'
      fullPath: '/quiz/edit/$id'
      preLoaderRoute: typeof QuizEditIdRouteImport
      parentRoute: typeof QuizRouteRoute
    }
    '/chapters/edit/$id': {
      id: '/chapters/edit/$id'
      path: '/edit/$id'
      fullPath: '/chapters/edit/$id'
      preLoaderRoute: typeof ChaptersEditIdRouteImport
      parentRoute: typeof ChaptersRouteRoute
    }
  }
}

interface ChaptersRouteRouteChildren {
  ChaptersIdRoute: typeof ChaptersIdRoute
  ChaptersAddRoute: typeof ChaptersAddRoute
  ChaptersEditIdRoute: typeof ChaptersEditIdRoute
}

const ChaptersRouteRouteChildren: ChaptersRouteRouteChildren = {
  ChaptersIdRoute: ChaptersIdRoute,
  ChaptersAddRoute: ChaptersAddRoute,
  ChaptersEditIdRoute: ChaptersEditIdRoute,
}

const ChaptersRouteRouteWithChildren = ChaptersRouteRoute._addFileChildren(
  ChaptersRouteRouteChildren,
)

interface QuizRouteRouteChildren {
  QuizIdRoute: typeof QuizIdRoute
  QuizAddRoute: typeof QuizAddRoute
  QuizEditIdRoute: typeof QuizEditIdRoute
}

const QuizRouteRouteChildren: QuizRouteRouteChildren = {
  QuizIdRoute: QuizIdRoute,
  QuizAddRoute: QuizAddRoute,
  QuizEditIdRoute: QuizEditIdRoute,
}

const QuizRouteRouteWithChildren = QuizRouteRoute._addFileChildren(
  QuizRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRoute,
  ChaptersRouteRoute: ChaptersRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRoute,
  QuestionsRouteRoute: QuestionsRouteRoute,
  QuizRouteRoute: QuizRouteRouteWithChildren,
  SubmissionsRouteRoute: SubmissionsRouteRoute,
  UsersRouteRoute: UsersRouteRoute,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
