/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as QuestionsRouteRouteImport } from './routes/questions/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubmissionsIndexRouteImport } from './routes/submissions/index'
import { Route as QuizIndexRouteImport } from './routes/quiz/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ChaptersIndexRouteImport } from './routes/chapters/index'
import { Route as QuizIdRouteImport } from './routes/quiz/$id'
import { Route as ChaptersAddRouteImport } from './routes/chapters/add'
import { Route as ChaptersIdRouteImport } from './routes/chapters/$id'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ChaptersEditIdRouteImport } from './routes/chapters/edit.$id'

const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRouteRoute = QuestionsRouteRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsIndexRoute = SubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIndexRoute = ChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersAddRoute = ChaptersAddRouteImport.update({
  id: '/chapters/add',
  path: '/chapters/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIdRoute = ChaptersIdRouteImport.update({
  id: '/chapters/$id',
  path: '/chapters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersEditIdRoute = ChaptersEditIdRouteImport.update({
  id: '/chapters/edit/$id',
  path: '/chapters/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/questions': typeof QuestionsRouteRoute
  '/users': typeof UsersRouteRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/chapters/$id': typeof ChaptersIdRoute
  '/chapters/add': typeof ChaptersAddRoute
  '/quiz/$id': typeof QuizIdRoute
  '/chapters': typeof ChaptersIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/submissions': typeof SubmissionsIndexRoute
  '/chapters/edit/$id': typeof ChaptersEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/questions': typeof QuestionsRouteRoute
  '/users': typeof UsersRouteRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/chapters/$id': typeof ChaptersIdRoute
  '/chapters/add': typeof ChaptersAddRoute
  '/quiz/$id': typeof QuizIdRoute
  '/chapters': typeof ChaptersIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/submissions': typeof SubmissionsIndexRoute
  '/chapters/edit/$id': typeof ChaptersEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/questions': typeof QuestionsRouteRoute
  '/users': typeof UsersRouteRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/chapters/$id': typeof ChaptersIdRoute
  '/chapters/add': typeof ChaptersAddRoute
  '/quiz/$id': typeof QuizIdRoute
  '/chapters/': typeof ChaptersIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/submissions/': typeof SubmissionsIndexRoute
  '/chapters/edit/$id': typeof ChaptersEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/questions'
    | '/users'
    | '/auth/sign-in'
    | '/chapters/$id'
    | '/chapters/add'
    | '/quiz/$id'
    | '/chapters'
    | '/dashboard'
    | '/quiz'
    | '/submissions'
    | '/chapters/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/questions'
    | '/users'
    | '/auth/sign-in'
    | '/chapters/$id'
    | '/chapters/add'
    | '/quiz/$id'
    | '/chapters'
    | '/dashboard'
    | '/quiz'
    | '/submissions'
    | '/chapters/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/questions'
    | '/users'
    | '/auth/sign-in'
    | '/chapters/$id'
    | '/chapters/add'
    | '/quiz/$id'
    | '/chapters/'
    | '/dashboard/'
    | '/quiz/'
    | '/submissions/'
    | '/chapters/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuestionsRouteRoute: typeof QuestionsRouteRoute
  UsersRouteRoute: typeof UsersRouteRoute
  AuthSignInRoute: typeof AuthSignInRoute
  ChaptersIdRoute: typeof ChaptersIdRoute
  ChaptersAddRoute: typeof ChaptersAddRoute
  QuizIdRoute: typeof QuizIdRoute
  ChaptersIndexRoute: typeof ChaptersIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  QuizIndexRoute: typeof QuizIndexRoute
  SubmissionsIndexRoute: typeof SubmissionsIndexRoute
  ChaptersEditIdRoute: typeof ChaptersEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/': {
      id: '/submissions/'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/': {
      id: '/chapters/'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/add': {
      id: '/chapters/add'
      path: '/chapters/add'
      fullPath: '/chapters/add'
      preLoaderRoute: typeof ChaptersAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$id': {
      id: '/chapters/$id'
      path: '/chapters/$id'
      fullPath: '/chapters/$id'
      preLoaderRoute: typeof ChaptersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/edit/$id': {
      id: '/chapters/edit/$id'
      path: '/chapters/edit/$id'
      fullPath: '/chapters/edit/$id'
      preLoaderRoute: typeof ChaptersEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuestionsRouteRoute: QuestionsRouteRoute,
  UsersRouteRoute: UsersRouteRoute,
  AuthSignInRoute: AuthSignInRoute,
  ChaptersIdRoute: ChaptersIdRoute,
  ChaptersAddRoute: ChaptersAddRoute,
  QuizIdRoute: QuizIdRoute,
  ChaptersIndexRoute: ChaptersIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  QuizIndexRoute: QuizIndexRoute,
  SubmissionsIndexRoute: SubmissionsIndexRoute,
  ChaptersEditIdRoute: ChaptersEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
